#!/bin/bash
#
#       /etc/rc.d/init.d/cb-event-forwarder
#
. /etc/init.d/functions

prog="cb-event-forwarder"
piddir="/var/run/cb/integrations/event-forwarder"
pidfile="$piddir/$prog.pid"
precommand="/usr/share/cb/integrations/event-forwarder/cb-event-forwarder -check /etc/cb/integrations/event-forwarder/cb-event-forwarder.conf"
command="/usr/share/cb/integrations/event-forwarder/cb-event-forwarder /etc/cb/integrations/event-forwarder/cb-event-forwarder.conf"

start() {
    if [ -f "$pidfile" ] && kill -0 $(cat "$pidfile"); then
        echo "Already started"
        return 1
    fi
    echo -n "Starting $prog: "
    $precommand &> /var/log/cb/integrations/cb-event-forwarder/cb-event-forwarder.startup.log
    result=$?
    if [ "$result" -ne "0" ]; then
        echo "Failed config file check"
        return $result
    fi
    nohup $command > /var/log/cb/integrations/cb-event-forwarder/cb-event-forwarder.log 2>&1 &
    PID=$(echo $!)
    result=$?

    if [ -z $PID ]; then
        echo "Failed"
    else
        mkdir -p $piddir
        echo $PID > $pidfile
        echo "Ok"
    fi
    return $result
}

stop() {
    echo -n "Shutting down $prog: "
    if [ ! -f "$pidfile" ] || ! kill -0 $(cat "$pidfile"); then
        echo "Ok"
        return 1
    fi
	kill -15 $(cat $pidfile) && rm -f $pidfile
	echo "Ok"
    return 0
}

status() {
    echo -n "Status of $prog: "
    if [ -f "$pidfile" ] && kill -0 $(cat "$pidfile"); then
        echo "Running"
    else
        echo "Stopped"
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        stop
        start
        ;;
esac
exit $?
