#!/bin/bash
#
#       /etc/rc.d/init.d/cb-event-forwarder
#
# chkconfig: 3456 20 80
. /etc/init.d/functions
/usr/share/cb/integrations/event-forwarder/cb-edr-event/cb-edr-fix-permissions.sh
prog="cb-event-forwarder"
piddir="/var/run/cb/integrations/event-forwarder"
pidfile="$piddir/$prog.pid"
precommand="/usr/share/cb/integrations/event-forwarder/cb-event-forwarder -check /etc/cb/integrations/event-forwarder/cb-event-forwarder.conf"
command="/usr/share/cb/integrations/event-forwarder/cb-event-forwarder -pid-file ${pidfile} /etc/cb/integrations/event-forwarder/cb-event-forwarder.conf"

start() {
    if [ -f "$pidfile" ]; then
        kill -0 $(cat "$pidfile")
        if [ $? -eq 0 ]; then
          echo "Already started"
          return 1
        fi
    fi

    echo -n "Starting $prog: "
    $precommand &> /var/log/cb/integrations/cb-event-forwarder/cb-event-forwarder.startup.log
    result=$?
    if [ "$result" -ne "0" ]; then
        echo "Failed config file check"
        return $result
    fi
    nohup $command &> /var/log/cb/integrations/cb-event-forwarder/cb-event-forwarder.log 2>&1 &
    PID=$(echo $!)
    result=$?
    if [ -z $PID ]; then
        echo "Failed"
    else
        echo "Ok"
    fi
    return $result
}

stop() {
    echo -n "Shutting down $prog: "
    if [ ! -f "$pidfile" ] || ! kill -0 $(cat "$pidfile"); then
        echo "Ok"
        return 0
    fi
    if kill -15 $(cat $pidfile) ; then
	rm -f $pidfile
	echo "Ok"
    	return 0
    else 
	echo "Failed"
	return 1
    fi
}

status() {
    echo -n "Status of $prog: "
    if [ -f "$pidfile" ] && kill -0 $(cat "$pidfile"); then
        echo "Running"
        return 0
    else
        echo "Stopped"
        return 1
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        stop
        start
        ;;
esac
exit $?
