version: '2.1'
services:
  eventforwarder:
    build:
      context: .
      args:
        INIFILE: cb-event-forwarder.docker.ini
    hostname: eventforwarder
    container_name: eventforwarder
    restart: always
    tty: true
    sysctls:
      net.ipv6.conf.all.disable_ipv6 :  1
    ports:
      - "33706:33706"
    depends_on:
      - rabbitmq
      - grafana
      - graphite

  grafana:
      image: grafana/grafana
      container_name: grafana
      hostname: grafana
      restart: always
      ports:
        - 3000:3000

  graphite:
      hostname: graphite
      image: graphiteapp/graphite-statsd
      container_name: graphite
      restart: always

  rabbitmq:
    image: "rabbitmq:3.6.5-management"
    hostname: "rabbitmq"
    volumes:
      - ./run/config/rabbitmq/definitions.json:/opt/definitions.json:ro
      - ./run/config/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
    ports:
      - "15672:15672"
      - "5672:5672"

  stressrabbit:
    build: ./test/stress_rabbit
    hostname: stressrabbit
    container_name: stressrabbit
    depends_on:
      - rabbitmq
      - eventforwarder

