version: '2.2'
services:
  eventforwarder:
    build:
      context: .
      args:
        INIFILE: cb-event-forwarder.dockerhttp.ini
        EFEXE: cb-event-forwarder
    hostname: eventforwarder
    container_name: eventforwarder
    restart: always
    cpu_count: 6
    tty: true
    environment:
      - EF_CANNED_INPUT=0
      - EF_RUN_CONSUMER=0
    sysctls:
      net.ipv6.conf.all.disable_ipv6 :  1
    ports:
      - "33706:33706"
    depends_on:
      - grafana
      - graphite
      - httpserver

  grafana:
      image: grafana/grafana
      container_name: grafana
      hostname: grafana
      restart: always
      ports:
        - 3000:3000

  graphite:
      hostname: graphite
      image: graphiteapp/graphite-statsd
      container_name: graphite
      restart: always

  httpserver:
      container_name: httpserver
      hostname: httpserver
      tty: true
      build:
        context: .
        dockerfile: Dockerfile.httpserver
      restart: always
