#!/bin/sh

echo -n $"Post Install"

chkconfig --add cb-forwarder-bridge

chkconfig --level 345 cb-forwarder-bridge on

# not auto-starting because conf needs to be updated
#/etc/init.d/cb-forwarder-bridge start
