#!/bin/sh

echo -n $"Post Install"

chkconfig --add cb-event-forwarder

chkconfig --level 345 cb-event-forwarder on

# not auto-starting because conf needs to be updated
#/etc/init.d/cb-event-forwarder start
