#!/usr/bin/env python

import os
import sys

import cbeventforwarder.bridge


if __name__ == "__main__":
    name = "cb-event-forwarder"
    daemon = cbeventforwarder.bridge.CarbonBlackEventForwarder(name, "/etc/cb/integrations/event-forwarder/cb-event-forwarder.conf")
    if len(sys.argv) == 2:
        if 'start' == sys.argv[1]:
            daemon.start()
        elif 'stop' == sys.argv[1]:
            daemon.stop()
        elif 'restart' == sys.argv[1]:
            daemon.restart()
        else:
            print "Unknown command: %s" % sys.argv[1]
            sys.exit(2)

    else:
        print "Usage: %s start|stop|restart|version" % sys.argv[0]
        sys.exit(2)

