services:
  event-forwarder:
    container_name: carbonblack-event-forwarder
    image: projects.registry.vmware.com/carbonblack/event-forwarder:latest
    volumes:
      - ./data/config/cb.conf:/etc/cb/cb.conf:ro
      - ./data/integrations:/etc/cb/integrations
      - ./data/config/integrations/event-forwarder:/root/event-forwarder-edr
      - ./data/logs/event-forwarder:/var/log/cb/integrations/cb-event-forwarder
    networks:
      - carbonblack
networks:
  carbonblack:
    external: true
