#!/usr/bin/env python

import os
import sys

import cbsplunkbridge.bridge


if __name__ == "__main__":
    name = "cbsplunkbridge"
    daemon = cbsplunkbridge.bridge.CarbonBlackSplunkBridge(name, "/etc/cb/integrations/cbsplunkbridge/cbsplunkbridge.conf")
    if len(sys.argv) == 2:
        if 'start' == sys.argv[1]:
            daemon.start()
        elif 'stop' == sys.argv[1]:
            daemon.stop()
        elif 'restart' == sys.argv[1]:
            daemon.restart()
        else:
            print "Unknown command: %s" % sys.argv[1]
            sys.exit(2)

    else:
        print "Usage: %s start|stop|restart|version" % sys.argv[0]
        sys.exit(2)

