#!/usr/bin/env python

import os
import sys

sys.path.insert(0, "../../lib/src/")


import cbforwarderbridge.bridge


if __name__ == "__main__":
    try:
        name = "cbforwarderbridge"
        daemon = cbforwarderbridge.bridge.CarbonBlackForwarderBridge(name, os.path.abspath("root/etc/cb/integrations/cbforwarderbridge/cbforwarderbridge.conf"))
        if len(sys.argv) == 2:
            if 'start' == sys.argv[1]:
                daemon.start()
            elif 'stop' == sys.argv[1]:
                daemon.stop()
            elif 'restart' == sys.argv[1]:
                daemon.restart()
            else:
                print "Unknown command: %s" % sys.argv[1]
                sys.exit(2)

        else:
            print "Usage: %s start|stop|restart|version" % sys.argv[0]
            sys.exit(2)
    except Exception, ex:
        sys.stderr("Test failed: %s", ex.message)
